[2024-05-22 14:01:14,015: INFO: main: Welcome]
[2024-05-22 20:16:30,222: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-22 20:16:30,222: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 20:16:30,222: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 20:16:30,222: INFO: common: created directory at: artifacts]
[2024-05-22 20:16:30,222: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-22 20:16:30,230: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yXkOfYmGqGMB1CvmD5qouaKV21f7jHVS/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 20:17:01,233: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yXkOfYmGqGMB1CvmD5qouaKV21f7jHVS/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 20:17:01,679: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-22 20:59:49,220: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 20:59:49,311: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 20:59:49,317: INFO: common: created directory at: artifacts]
[2024-05-22 20:59:49,317: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-22 20:59:57,649: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 20:59:57,655: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 20:59:57,658: INFO: common: created directory at: artifacts]
[2024-05-22 20:59:57,658: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-22 21:00:07,339: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 21:00:07,339: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 21:00:07,345: INFO: common: created directory at: artifacts]
[2024-05-22 21:00:07,345: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-22 21:02:05,347: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 21:02:05,358: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 21:02:05,358: INFO: common: created directory at: artifacts]
[2024-05-22 21:02:05,360: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-22 21:02:05,748: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-22 21:02:05,982: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-22 21:28:22,520: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-22 21:28:22,521: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 21:28:22,526: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 21:28:22,529: INFO: common: created directory at: artifacts]
[2024-05-22 21:28:22,530: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-22 21:28:22,530: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yXkOfYmGqGMB1CvmD5qouaKV21f7jHVS/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 21:28:56,148: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yXkOfYmGqGMB1CvmD5qouaKV21f7jHVS/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 21:28:56,699: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-22 21:28:56,700: INFO: main: *******************]
[2024-05-22 21:28:56,700: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-22 21:28:56,700: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 21:28:56,701: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 21:28:56,703: INFO: common: created directory at: artifacts]
[2024-05-22 21:28:56,703: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-22 21:28:57,217: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-22 21:28:57,475: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-22 21:28:58,173: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-22 21:59:04,748: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 21:59:04,836: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 21:59:04,836: INFO: common: created directory at: artifacts]
[2024-05-22 21:59:04,836: INFO: common: created directory at: artifacts\training]
[2024-05-22 21:59:06,682: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-22 22:22:09,943: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-22 22:22:09,945: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:22:09,950: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 22:22:09,952: INFO: common: created directory at: artifacts]
[2024-05-22 22:22:09,953: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-22 22:22:09,953: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yXkOfYmGqGMB1CvmD5qouaKV21f7jHVS/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:22:42,686: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yXkOfYmGqGMB1CvmD5qouaKV21f7jHVS/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:22:43,173: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-22 22:22:43,173: INFO: main: *******************]
[2024-05-22 22:22:43,173: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-22 22:22:43,173: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:22:43,173: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 22:22:43,173: INFO: common: created directory at: artifacts]
[2024-05-22 22:22:43,173: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-22 22:22:43,482: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-22 22:22:43,623: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-22 22:22:43,720: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-22 22:22:43,720: INFO: main: *******************]
[2024-05-22 22:22:43,720: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-22 22:22:43,724: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:22:43,724: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 22:22:43,724: INFO: common: created directory at: artifacts]
[2024-05-22 22:22:43,724: INFO: common: created directory at: artifacts\training]
[2024-05-22 22:22:43,865: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-22 22:22:43,865: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "F:\kidney_diseases_classification\main.py", line 35, in <module>
    model_trainer.main()
  File "F:\kidney_diseases_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "F:\kidney_diseases_classification\src\cnnClassifier\components\model_training.py", line 39, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mallik\AppData\Roaming\Python\Python311\site-packages\keras\src\legacy\preprocessing\image.py", line 1138, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mallik\AppData\Roaming\Python\Python311\site-packages\keras\src\legacy\preprocessing\image.py", line 453, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-05-22 22:27:55,341: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-22 22:27:55,341: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:27:55,341: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 22:27:55,341: INFO: common: created directory at: artifacts]
[2024-05-22 22:27:55,341: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-22 22:27:55,341: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yXkOfYmGqGMB1CvmD5qouaKV21f7jHVS/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:28:26,582: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yXkOfYmGqGMB1CvmD5qouaKV21f7jHVS/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:28:27,091: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-22 22:28:27,091: INFO: main: *******************]
[2024-05-22 22:28:27,091: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-22 22:28:27,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:28:27,091: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 22:28:27,091: INFO: common: created directory at: artifacts]
[2024-05-22 22:28:27,091: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-22 22:28:27,381: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-22 22:28:27,540: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-22 22:28:27,623: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-22 22:28:27,623: INFO: main: *******************]
[2024-05-22 22:28:27,623: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-22 22:28:27,623: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:28:27,632: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 22:28:27,632: INFO: common: created directory at: artifacts]
[2024-05-22 22:28:27,632: INFO: common: created directory at: artifacts\training]
[2024-05-22 22:28:27,776: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-22 22:28:28,893: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 4), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "F:\kidney_diseases_classification\main.py", line 35, in <module>
    model_trainer.main()
  File "F:\kidney_diseases_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "F:\kidney_diseases_classification\src\cnnClassifier\components\model_training.py", line 78, in train
    self.model.fit(
  File "C:\Users\Mallik\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Mallik\AppData\Roaming\Python\Python311\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 4), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-05-22 22:34:09,361: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-22 22:34:09,361: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:34:09,361: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 22:34:09,361: INFO: common: created directory at: artifacts]
[2024-05-22 22:34:09,361: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-22 22:34:09,377: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yXkOfYmGqGMB1CvmD5qouaKV21f7jHVS/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:34:41,764: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yXkOfYmGqGMB1CvmD5qouaKV21f7jHVS/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:34:42,240: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-22 22:34:42,240: INFO: main: *******************]
[2024-05-22 22:34:42,240: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-22 22:34:42,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:34:42,256: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 22:34:42,256: INFO: common: created directory at: artifacts]
[2024-05-22 22:34:42,256: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-22 22:34:42,541: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-22 22:34:42,692: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-22 22:34:42,772: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-22 22:34:42,772: INFO: main: *******************]
[2024-05-22 22:34:42,772: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-22 22:34:42,772: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:34:42,772: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-22 22:34:42,786: INFO: common: created directory at: artifacts]
[2024-05-22 22:34:42,786: INFO: common: created directory at: artifacts\training]
[2024-05-22 22:34:42,956: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-22 22:34:43,672: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 4), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "F:\kidney_diseases_classification\main.py", line 35, in <module>
    model_trainer.main()
  File "F:\kidney_diseases_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "F:\kidney_diseases_classification\src\cnnClassifier\components\model_training.py", line 78, in train
    self.model.fit(
  File "C:\Users\Mallik\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Mallik\AppData\Roaming\Python\Python311\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 4), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
